CREATE DATABASE IF NOT EXISTS kasir_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE kasir_db;

-- 1. TABEL LAPORAN UTAMA
CREATE TABLE IF NOT EXISTS laporan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tanggal DATE NOT NULL,
  UNIQUE KEY uk_tanggal (tanggal),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 2. TABEL KASIR APOTEK
CREATE TABLE IF NOT EXISTS kasir_apotek (
  id INT AUTO_INCREMENT PRIMARY KEY,
  laporan_id INT NOT NULL,
  kas_awal DECIMAL(15,2) NOT NULL DEFAULT 0,
  penjualan_resep DECIMAL(15,2) NOT NULL DEFAULT 0,
  penjualan_bebas DECIMAL(15,2) NOT NULL DEFAULT 0,
  jm_dr_zainuddin DECIMAL(15,2) NOT NULL DEFAULT 0,
  jm_dr_ali_program DECIMAL(15,2) NOT NULL DEFAULT 0,
  jm_dr_ali_non_program DECIMAL(15,2) NOT NULL DEFAULT 0,
  transfer DECIMAL(15,2) NOT NULL DEFAULT 0,
  FOREIGN KEY (laporan_id) REFERENCES laporan(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pengeluaran_apotek (
  id INT AUTO_INCREMENT PRIMARY KEY,
  laporan_id INT NOT NULL,
  keterangan VARCHAR(255) DEFAULT '',
  nominal DECIMAL(15,2) NOT NULL DEFAULT 0,
  urutan TINYINT UNSIGNED NOT NULL DEFAULT 0,
  FOREIGN KEY (laporan_id) REFERENCES laporan(id) ON DELETE CASCADE
);

-- 3. TABEL KASIR PENDAFTARAN
CREATE TABLE IF NOT EXISTS kasir_pendaftaran (
  id INT AUTO_INCREMENT PRIMARY KEY,
  laporan_id INT NOT NULL,
  kas_awal DECIMAL(15,2) NOT NULL DEFAULT 0,
  fisio_120_pasien INT NOT NULL DEFAULT 0,
  fisio_90_pasien INT NOT NULL DEFAULT 0,
  admin_gigi_mata DECIMAL(15,2) NOT NULL DEFAULT 0,
  admin_pasien_baru_count INT NOT NULL DEFAULT 0,
  parkir DECIMAL(15,2) NOT NULL DEFAULT 0,
  FOREIGN KEY (laporan_id) REFERENCES laporan(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lab_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  laporan_id INT NOT NULL,
  nominal DECIMAL(15,2) NOT NULL DEFAULT 0,
  urutan TINYINT UNSIGNED NOT NULL DEFAULT 0,
  FOREIGN KEY (laporan_id) REFERENCES laporan(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pengeluaran_pend (
  id INT AUTO_INCREMENT PRIMARY KEY,
  laporan_id INT NOT NULL,
  keterangan VARCHAR(255) DEFAULT '',
  nominal DECIMAL(15,2) NOT NULL DEFAULT 0,
  urutan TINYINT UNSIGNED NOT NULL DEFAULT 0,
  FOREIGN KEY (laporan_id) REFERENCES laporan(id) ON DELETE CASCADE
);

-- 4. TABEL ABSENSI & HARI KERJA KARYAWAN
CREATE TABLE IF NOT EXISTS employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  position VARCHAR(100) NOT NULL,
  schedule_type ENUM('NORMAL','APOTEKER','SECURITY','CLEANING_SERVICE') NOT NULL DEFAULT 'NORMAL',
  active TINYINT(1) NOT NULL DEFAULT 1,
  start_date DATE NULL,
  end_date DATE NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS holidays (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date DATE NOT NULL UNIQUE,
  name VARCHAR(150) NOT NULL,
  description TEXT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attendance_notes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  employee_id INT NOT NULL,
  type ENUM('sakit','izin','cuti') NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  notes TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS work_periods (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status ENUM('active','closed') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  setting_key VARCHAR(100) NOT NULL UNIQUE,
  setting_value JSON NOT NULL,
  description TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
