CREATE DATABASE IF NOT EXISTS kasir_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE kasir_db;

CREATE TABLE IF NOT EXISTS laporan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tanggal DATE NOT NULL,
  UNIQUE KEY uk_tanggal (tanggal),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kasir_apotek (
  id INT AUTO_INCREMENT PRIMARY KEY,
  laporan_id INT NOT NULL,
  kas_awal DECIMAL(15,2) NOT NULL DEFAULT 0,
  penjualan_resep DECIMAL(15,2) NOT NULL DEFAULT 0,
  penjualan_bebas DECIMAL(15,2) NOT NULL DEFAULT 0,
  jm_dr_zainuddin DECIMAL(15,2) NOT NULL DEFAULT 0,
  jm_dr_ali_program DECIMAL(15,2) NOT NULL DEFAULT 0,
  jm_dr_ali_non_program DECIMAL(15,2) NOT NULL DEFAULT 0,
  transfer DECIMAL(15,2) NOT NULL DEFAULT 0,
  FOREIGN KEY (laporan_id) REFERENCES laporan(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pengeluaran_apotek (
  id INT AUTO_INCREMENT PRIMARY KEY,
  laporan_id INT NOT NULL,
  keterangan VARCHAR(255) DEFAULT '',
  nominal DECIMAL(15,2) NOT NULL DEFAULT 0,
  urutan TINYINT UNSIGNED NOT NULL DEFAULT 0,
  FOREIGN KEY (laporan_id) REFERENCES laporan(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS kasir_pendaftaran (
  id INT AUTO_INCREMENT PRIMARY KEY,
  laporan_id INT NOT NULL,
  kas_awal DECIMAL(15,2) NOT NULL DEFAULT 0,
  fisio_120_pasien INT NOT NULL DEFAULT 0,
  fisio_90_pasien INT NOT NULL DEFAULT 0,
  admin_gigi_mata DECIMAL(15,2) NOT NULL DEFAULT 0,
  admin_pasien_baru_count INT NOT NULL DEFAULT 0,
  parkir DECIMAL(15,2) NOT NULL DEFAULT 0,
  FOREIGN KEY (laporan_id) REFERENCES laporan(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lab_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  laporan_id INT NOT NULL,
  nominal DECIMAL(15,2) NOT NULL DEFAULT 0,
  urutan TINYINT UNSIGNED NOT NULL DEFAULT 0,
  FOREIGN KEY (laporan_id) REFERENCES laporan(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pengeluaran_pend (
  id INT AUTO_INCREMENT PRIMARY KEY,
  laporan_id INT NOT NULL,
  keterangan VARCHAR(255) DEFAULT '',
  nominal DECIMAL(15,2) NOT NULL DEFAULT 0,
  urutan TINYINT UNSIGNED NOT NULL DEFAULT 0,
  FOREIGN KEY (laporan_id) REFERENCES laporan(id) ON DELETE CASCADE
);
